config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'admin/pages#dashboard'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        sessions: 'api/v1/auth/sessions',
        registrations: 'api/v1/auth/registrations'
      }
      resources :strips, only: [] do
        post 'validate', on: :collection
      end
      resources :tests, only: [:create]
    end
  end

  namespace :admin do
    resources :tests, only: [:index]
    resources :strip_batches, only: [:create, :index, :new] do
      resources :strips, only: [:index]
    end
    resources :hormones, only: [:create, :index, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/test_type.rb
module TestType
  extend ActiveSupport::Concern
  included do
    enum test_type: { pregnancy: 0, ovulation: 1 }
  end
end

app/models/hormone.rb
class Hormone < ApplicationRecord
  before_validation :downcase_fields

  has_many :strip_batch_hormones
  has_many :strip_batches, through: :strip_batch_hormones
  has_many :test_hormones
  has_many :tests, through: :test_hormones

  validates :name, uniqueness: true ,presence: true, length: { minimum: 2, maximum: 20 }

  def downcase_fields
    self.name.downcase!
  end
end

app/models/strip.rb
class Strip < ApplicationRecord
  before_create :add_strip_code
  belongs_to :strip_batch
  has_one :test
  enum status: { active: 0, used: 1, damaged: 2 }
  validates :status, inclusion: { in: statuses.keys, message: :invalid }

  def self.get_validated_strip(strip_code, test_type)
    strip = self.find_by(code: strip_code)
    strip&.strip_batch&.test_type == test_type && strip.active? && strip.strip_batch.expd > Date.current && strip
  end

  private

  def add_strip_code
    self.code = SecureRandom.uuid
  end
end

app/models/strip_batch.rb
class StripBatch < ApplicationRecord
  include TestType

  before_save :downcase_fields
  before_create :create_strips

  has_many :strips
  has_many :strip_batch_hormones
  has_many :hormones, through: :strip_batch_hormones

  validates :manufacturer, presence: true
  validates :test_type, inclusion: { in: test_types.keys, message: :invalid }
  validates :batch_size, presence: true, inclusion: 1..99999
  validates :mfd, presence: true
  validates :expd, presence: true
  validate :one_hormone_at_least
  validate :validate_date

  private

  def validate_date
    unless expd > Date.current && expd > mfd
      errors.add(:expd, "Invalid date")
      errors.add(:mfd, "Invalid date")
    end
  end

  def downcase_fields
    self.manufacturer.downcase!
  end

  def one_hormone_at_least
    if self.hormones.empty?
      errors.add(:hormones, "Need at least one hormone")
    end
  end

  def create_strips
    batch_size.times do
      self.strips << Strip.new
    end
  end
end

app/models/strip_batch_hormone.rb
class StripBatchHormone < ApplicationRecord
  belongs_to :strip_batch
  belongs_to :hormone
end

app/models/test.rb
class Test < ApplicationRecord
  include TestType
  attr_accessor :strip_code
  after_create :change_strip_status
  belongs_to :user
  belongs_to :strip
  has_many :test_hormones
  has_many :hormones, through: :test_hormones
  validates :test_type, inclusion: { in: test_types.keys }

  private
  def change_strip_status
    strip.used!
  end
end

app/models/test_hormone.rb
class TestHormone < ApplicationRecord
  belongs_to :test
  belongs_to :hormone
  validates :concentration, presence: true
  validates :od_value, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable, :trackable
  include DeviseTokenAuth::Concerns::User
  enum role: { customer: 0, admin: 1 }
  validates :role, inclusion: { in: roles.keys }
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ::ApplicationController

    before_action :require_logged_in_auth_user
    before_action :authenticate_user!

    private

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end

    def require_logged_in_auth_user
      unless current_user&.admin?
        flash[:alert] = "You dont have enough permissions"
        sign_out current_user
        redirect_to user_session_url
      end
    end
  end

end

app/controllers/admin/hormones_controller.rb
module Admin
  class HormonesController < ::ApplicationController
    before_action :create_hormone, only: [:create, :new]

    def index
      @hormones = Hormone.all
    end

    def new
    end

    def create
      @hormone = Hormone.new(validated_hormone_params)
      if @hormone.save
        redirect_to admin_hormones_path
      else
        render 'new'
      end
    end

    private

    def create_hormone
      @hormone = Hormone.new
    end

    def validated_hormone_params
      params.require(:hormone).permit(:name)
    end
  end
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < ApplicationController
    def dashboard
    end
  end
end

app/controllers/admin/strip_batches_controller.rb
module Admin
  class StripBatchesController < ApplicationController
    before_action :create_strip_batch, only: [:create, :new]

    def index
      @strip_batches = StripBatch.all
    end

    def new
    end

    def create
      @strip_batch = StripBatch.new(validated_params)
      if @strip_batch.save
        redirect_to admin_strip_batches_path, notice: "Batch created successfully"
      else
        flash.now[:alert] = "Something went wrong"
        render 'new'
      end
    end

    private

    def create_strip_batch
      @strip_batch = StripBatch.new
    end

    def validated_params
      params.require(:strip_batch).permit(:manufacturer, :expd, :mfd, :test_type, :batch_size, :hormone_ids => [])
    end
  end
end

app/controllers/admin/strips_controller.rb
module Admin
  class StripsController < ApplicationController
    def index
      @strips = Strip.where(strip_batch_id: params[:strip_batch_id])
    end
  end
end

app/controllers/admin/tests_controller.rb
module Admin
  class TestsController < ApplicationController
    def index
      @tests = Test.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/pages/dashboard.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Inito</h1>
    <p class="lead">OK</p>
    <hr class="my-4">
    <p>OK</p>
    <%#= link_to "Logout!", , class: "btn btn-success btn-lg" %>
    <%#= link_to "Registered users!", new_user_session_path, class: "btn btn-success btn-lg" %>
    <%= link_to "Tests!", admin_tests_path, class: "btn btn-success btn-lg" %>
    <%= link_to "Strip batches!", admin_strip_batches_path, class: "btn btn-success btn-lg" %>
    <%= link_to "Hormones!", admin_hormones_path, class: "btn btn-success btn-lg" %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete %>

  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAssgn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
  <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Inito</h1>
    <p class="lead">OK</p>
    <hr class="my-4">
    <p>OK</p>
    <%= link_to "Login!", login_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>